### ISSUE TITLE
Can we get rid of org.apache.logging.log4j?

### ISSUE THREAD

**Issue by nh13** [Intel-HLS/GKL#100]
For such a low-level library, I'd rather not have it as a dependency (so it will get rolled into my assembly jar), and certainly not have its logging info on the console.  Can we just get rid of it and log to a file or somewhere else?

**Comment by nh13** [comment]
This is motivated by trying to keep the JAR size of fgbio as small as possible.  https://github.com/fulcrumgenomics/fgbio/pull/483.  Another idea that could help is having the inflater/deflater parts of the code in a separate JAR than the SW/HMM portions, so we don't have to include the latter.  

Examining the size of the dependencies included (using [this gist](https://gist.github.com/medvedev/968119d7786966d9ed4442ae17aca279)) we see:
```
Total dependencies size:                           4.52 Mb

htsjdk-2.9.0.jar                               1,528.30 kb
log4j-core-2.5.jar                             1,080.17 kb
snappy-java-1.0.3-rc3.jar                        967.05 kb
commons-jexl-2.1.1.jar                           261.36 kb
commons-compress-1.4.1.jar                       235.71 kb
commons-io-2.4.jar                               180.80 kb
log4j-api-2.5.jar                                143.32 kb
xz-1.5.jar                                        97.22 kb
ngs-java-1.2.4.jar                                72.40 kb
commons-logging-1.1.1.jar                         59.26 kb
gatk-native-bindings-0.1.0-rc-1.jar                6.33 kb
```

**Comment by nh13** [comment]
Could we not just use `commons-logging`, or the logging in `htsjdk`?

**Comment by mepowers** [comment]
Hi @nh13 - thanks for the input.  We're reviewing this suggestion this week.  I don't see any issue with logging elsewhere as you suggest.  Which GKL components does fgbio use?  The Deflater?

**Comment by nh13** [comment]
@mepowers we are starting to use the inflater and deflater.  This was also an issue in GATK and Picard (https://github.com/broadinstitute/picard/issues/883).  They solved it by adding a configuration file and muting the logging, but that means they also include the log4j transitive dependency, making the JAR they distribute larger.

**Comment by pditommaso** [comment]
Log4j can be replaced with the `log4j-over-slf4j` bridge API and the redirected to the Java stock logging API using the `slf4j-jdk14` adaptor. See for details [here](https://www.slf4j.org/legacy.html).

**Comment by nh13** [comment]
@pdtommaso thank-you! I did see that but I am trying to reduce the number of dependencies so I am not thrilled to include a few more to bridge the logging frameworks. I’ll look how much size they add.

**Comment by mepowers** [comment]
@nh13 - we discussed this internally as a team today and unfortunately updating the logging isn't a priority right now.  We do not have plans to change this.

**Comment by nh13** [comment]
Would you accept a PR to remove logging?

**Comment by mepowers** [comment]
@nh13 - we wouldn't.  We're only requesting PRs for bug fixes.
