### ISSUE TITLE
Systematically test the GKL deflater/inflater with long reads data

### ISSUE THREAD

**Issue by droazen** [Intel-HLS/GKL#105]
We suspect there may be performance and/or correctness bugs when running the GKL with long reads data, so we'd like to do some systematic testing of the library (particularly the deflater/inflater code) to determine what the state of long reads support is.

@jonn and/or someone on the long reads team at the Broad can provide suitable test data

**Comment by droazen** [comment]
Tentative testing plan: run several roundtrip full-scale tests in which we read in every record in a long reads bam file using the inflater to decompress, and write out a new bam using the deflater to re-compress. Then check the new bam against the original to make sure they're the same once uncompressed.

**Comment by droazen** [comment]
@jonn suggested that we also test long reads data with the accelerated SmithWaterman implementation in the GKL, just to see if it can handle long reads.

**Comment by jonn-smith** [comment]
I collected several test files with long reads and sent over some signed URLs for testing on 5/1.  I'm keeping them around if other folks need access (just let me know).

**Comment by droazen** [comment]
@kmannth has confirmed that they've received the long reads test data @jonn-smith sent them.

**Comment by Kmannth** [comment]
We tested Long Reads data form @jonn-smith with our latest release. If there is an issue please reopen this bug.
