### ISSUE TITLE
Run valgrind on the GKL codebase

### ISSUE THREAD

**Issue by droazen** [Intel-HLS/GKL#107]
Maybe it can catch some of these pointer safety issues reported in other tickets...

**Comment by Kmannth** [comment]
@droazen  Do happen to have BKMs for Valgrind and GATK?   We have  spent some time trying to get symbol resoltion for GATK and GKL with valgrind but so far not much sucess.

**Comment by Kmannth** [comment]
Summary:   The Valgrind and Java do not work well.   https://github.com/Intel-HLS/GKL/pull/91 was updated to run with Master was was last tested Jan 2021.   We will work to run this test as part of our regular  release process. 

With the latest code base and the limtied unit test cases no errors were found.
