### ISSUE TITLE
How to make the system use these libraries?

### ISSUE THREAD

**Issue by mepowers** [Intel-HLS/GKL#111]
Hi, I'm also missing some documentation how to make the system use these libraries... Do I need to set LD_LIBRARY_PATH? Do I have to move those files somewhere?

_Originally posted by @TekTimmy in https://github.com/Intel-HLS/GKL/issues/93#issuecomment-562083192_

**Comment by Kmannth** [comment]
t looks like the quesiton is how to use the GKL with BWA? 

In general GKL has not integrated with BWA to date. A develment level of integration work is required that is not if focuse for us at this point. 

Let us know if you will take this development effort on.
