### ISSUE TITLE
GATK4 HaplotypeCaller native SmithWaterman: core dumps and JVM errors

### ISSUE THREAD

**Issue by nh13** [Intel-HLS/GKL#113]
See test case in: https://github.com/broadinstitute/gatk/issues/6733

**Comment by mepowers** [comment]
@nh13 see comment here:  https://github.com/broadinstitute/gatk/issues/6733#issuecomment-674241524

**Comment by pkolakow** [comment]
This issue has been fixed here https://github.com/Intel-HLS/GKL/pull/142. The patch for this bug will come out with the next release.
