### ISSUE TITLE
Release 0.8.9 is not on maven

### ISSUE THREAD

**Issue by nh13** [Intel-HLS/GKL#170]
See: https://mvnrepository.com/artifact/com.intel.gkl/gkl.  Latest is 0.8.8.  Also, the release name has a `v` in it.  Thanks for the quick patch updating log4j!

**Comment by nh13** [comment]
Blocking an `fgbio` release: https://github.com/fulcrumgenomics/fgbio/pull/676

**Comment by Kmannth** [comment]
Our plan is to push a new 0.8.10 to maven in the next week or so.

**Comment by mateuszsnowak** [comment]
GKL 0.8.10 is currently present in maven repository.
