### ISSUE TITLE
Add javah support to CMake

### ISSUE THREAD

**Issue by gspowley** [Intel-HLS/GKL#37]
Generate JNI header files as needed using CMake.

**Comment by mepowers** [comment]
Snehal thinks this may have laready been done - we'll look into this

**Comment by mepowers** [comment]
Discussed as a team; not prioritizing at this point.  Closing this ticket.

From Snehal:

For issue#37 - seems *.h files are committed in repo, and not included in cmakeList. But this would need modifying all 3 modules.
Reference:
https://github.com/Intel-HLS/GKL/blob/master/src/main/native/smithwaterman/CMakeLists.txt
https://github.com/Intel-HLS/GKL/blob/master/src/main/native/pairhmm/IntelPairHmm.h
