### ISSUE TITLE
Potential memory leak in IntelDeflater

### ISSUE THREAD

**Issue by gspowley** [Intel-HLS/GKL#52]
We need to free the memory allocated for huffman tables on [this line of IntelDeflater.cc](https://github.com/Intel-HLS/GKL/blob/7c27959c4eb993d5dd9c29dcc68893f3c4acda90/src/main/native/compression/IntelDeflater.cc#L221), unless the ISA-L code is doing that for us.

**Comment by gspowley** [comment]
@pnvaidya can you please take a look at this on Monday?

**Comment by pnvaidya** [comment]
You are right, since we are allocating the tables in our code, we will have to clean it up, not ISAL…

if (level != 1) {
    deflateEnd(lz_stream);
  }
  else
  {
    free(hufftables_custom);
    free(lz_stream);
  }

Let me add this change to existing pull request.

**Comment by gspowley** [comment]
Resolved by #51
