### ISSUE TITLE
IntelDeflaterFactory should try to load the GKL at instance creation or class loading time

### ISSUE THREAD

**Issue by akiezun** [Intel-HLS/GKL#8]
IntelDeflaterFactory does not load the GKL until makeDeflater is called. This is too late because I want to know what deflater *will* be used before any deflater is actually created. See https://github.com/broadinstitute/gatk/tree/ak_use_intelDeflaterFactory and the workaround i put in CommandLineProgram for this issue.

**Comment by gspowley** [comment]
Fixed in release 0.1.1
