### ISSUE TITLE
GATK v3.8 GKL memory issues?

### ISSUE THREAD

**Issue by sooheelee** [Intel-HLS/GKL#81]
Could I get a consult on GATK user questions at <https://gatkforums.broadinstitute.org/gatk/discussion/10353/gatk-3-8-0-printreads-fatal-error#latest>? 

Users are experiencing issues for v3.8 of GATK, which implements the GKL by default. I'm not sure if the issues are related to GKL, and if they are what are the guidelines we should provide users experiencing such issues.

Thanks.

**Comment by sooheelee** [comment]
Could @erniebrau or @pnvaidya please forward this issue to relevant persons? I've just grabbed your handles because you appear active in this repo. Much appreciated.

**Comment by gspowley** [comment]
@sooheelee, We are looking into the issues reported in the GATK discussion list. If GKL is causing the issues, then users should add the `-jdk_deflater` and `-jdk_inflater` options to GATK until we resolve the issue.

**Comment by sooheelee** [comment]
Thank you. We look forward to hearing back from you and your team.

**Comment by lbergelson** [comment]
Another similar report in picard.  https://github.com/broadinstitute/picard/issues/975
