### ISSUE TITLE
Error:  error: ‘__m512’ does not name a type 

### ISSUE THREAD

**Issue by haiwufan** [Intel-HLS/GKL#86]
Hi Developer,
I meet some error when I install GKL. Could you help me to solve this problem?

Install command and error info as below:

*****************************************
root@cgvm-bk-r3:/pub/bin/GKL# ./gradlew test
:compileJava UP-TO-DATE
:cmakeConfig
:cmakeBuild
In file included from /pub/bin/GKL/src/main/native/pairhmm/avx-pairhmm.h:5:0,
                 from /pub/bin/GKL/src/main/native/pairhmm/avx_impl.cc:2:
/pub/bin/GKL/src/main/native/pairhmm/avx-types.h:8:17: error: ‘__m512’ does not name a type
         ALIGNED __m512 ALIGNED d;
                 ^
/pub/bin/GKL/src/main/native/pairhmm/avx-types.h:11:17: error: ‘__m512i’ does not name a type
         ALIGNED __m512i ALIGNED i;
                 ^
/pub/bin/GKL/src/main/native/pairhmm/avx-types.h:71:17: error: ‘__m512d’ does not name a type
         ALIGNED __m512d ALIGNED d;
                 ^
/pub/bin/GKL/src/main/native/pairhmm/avx-types.h:74:17: error: ‘__m512i’ does not name a type
         ALIGNED __m512i ALIGNED i;
                 ^
make[2]: *** [src/main/native/pairhmm/CMakeFiles/gkl_pairhmm.dir/avx_impl.cc.o] Error 1
make[1]: *** [src/main/native/pairhmm/CMakeFiles/gkl_pairhmm.dir/all] Error 2
make: *** [all] Error 2
:cmakeBuild FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':cmakeBuild'.
> Process 'command 'make'' finished with non-zero exit value 2

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED
*****************************************

**Comment by gspowley** [comment]
@haiwufan this error means your C++ compiler does not support AVX-512. Please try a newer compiler with AVX-512 support (for example `GCC 5.3.1`).

**Comment by gspowley** [comment]
The README now includes detailed build instructions.
