### ISSUE TITLE
Uninitialized pointer in IntelDeflater.cc

### ISSUE THREAD

**Issue by mirounga** [Intel-HLS/GKL#89]
Memory at uninitialized pointer is being written to [here](https://github.com/Intel-HLS/GKL/blob/964ccf058ce43cf5eb48cb1e8e26965b40003b20/src/main/native/compression/IntelDeflater.cc#L170)

**Comment by gspowley** [comment]
@pnvaidya can you please take a look at this?

**Comment by mepowers** [comment]
We're working on a new release - will check this and confirm it's resolved with latest version of GKL.

**Comment by Kmannth** [comment]
https://github.com/Intel-HLS/GKL/pull/114 has an inital fix for this issue.

**Comment by Kmannth** [comment]
The patch has been landed to Master please retest and let us know if you still see the issue.
