### ISSUE TITLE
Create new Thread in Mutect2 will slow down the omp and avx accelerated pairHMM calculation?

### ISSUE THREAD

**Issue by cxfustc** [Intel-HLS/GKL#90]
Hi Developer,

I was trying to accelerate Mutect2. I used class Thread to create new threads to parallelize the data prepare and active region calculation. However, after this modification, the calculation of pairHMM was much slower than before using the same data. I used the GKL source code with the commit id 'a6f5f4'.

Thank you very much!

**Comment by gspowley** [comment]
My guess is some of the cores previously used for PairHMM are now used for preparing active regions.

**Comment by cxfustc** [comment]
Thank you for replying.

[https://github.com/cxfustc/Tiny_GKL_test/blob/master/PairHMMTest.java](url)
I write a simple test code, and it comes out you are right. It is the competition for cores that slows down the calculation speed.

Here is the test result. The computer for testing has 4 cores.
If the number of threads for every pairhmm engine is set to 1. The result of the program is:
Cost 4.527874s
Cost 3.670908s
Cost 4.456890s
Cost 4.555578s
Cost 4.757390s
If the number of threads is set to 2. The result of the program is:
Cost 1.798678s
Cost 2.841058s
Cost 3.018658s
Cost 3.194318s
Cost 3.424579s
