### ISSUE TITLE
Smith Waterman requires GATK classes to use

### ISSUE THREAD

**Issue by d-cameron** [Intel-HLS/GKL#92]
No GATK-independent API is provided for the accelerated smith waterman implementation. It would be quite useful to be able to use this implementation to replace http://jaligner.sourceforge.net or the java bindings I wrote for https://github.com/mengyao/Complete-Striped-Smith-Waterman-Library.

Are there any plans to release a stand-alone AVX accelerated S/W implementation?

**Comment by gspowley** [comment]
PR #91 provides a way to build Smith-Waterman and PairHMM in a standalone C library. It hasn't been merged yet because we haven't had time to review it.

If you would like to give the PR a try, we would welcome your feedback.

**Comment by lbergelson** [comment]
@d-cameron Maybe I misunderstand, but the only GATK dependency in GKL is https://github.com/broadinstitute/gatk-native-bindings which is a totally independent library that is dependency free.  It doesn't pull in the whole GATK.
