### ISSUE TITLE
Can this library be used to accelerate Smith Waterman algorithm powered software, like bwa?

### ISSUE THREAD

**Issue by sfchen** [Intel-HLS/GKL#93]
If yes, is there any introduction, or any benchmark?

**Comment by TekTimmy** [comment]
Hi, I'm also missing some documentation how to make the system use these libraries... Do I need to set LD_LIBRARY_PATH? Do I have to move those files somewhere?

**Comment by mepowers** [comment]
@sfchen - the short answer is yes.  The AVX-512 Smith Waterman Kernel can be used by any tool that uses Smith Waterman.  The longer answer is we haven't done this engineering work.  
@TekTimmy - I spun your Q out into a separate issue.  Our team will address it over there (https://github.com/Intel-HLS/GKL/issues/111)
