### ISSUE TITLE
FPGA PairHMM : calculate() stub for double precision

### ISSUE THREAD

**Issue by rick-heig** [Intel-HLS/GKL#97]
Could you add a `calculateDouble()` stub function for double precision FPGA implementations ?

This would allow FPGA developers to create FPGA double precision implementation that are compatible with the GKL. Since none of the other interfaces change, this change will not affect any other software using GKL.

This would require : 
- Adding the stub in the `shacc_pairhmm` namespace
- Change the allocation of the result table in JavaData.h (line 105, 106) to double (this would still work with the float version but use 2x the memory) or create a specific `getBatchDouble()` function.
```
// allocate results
m_batch.results = (float*)malloc(sizeof(float) * num_testcases); // Change to (double*)
```
-  Change the `if (g_use_fpga && !g_use_double)` in IntelPairHmm.cc to
```
if (g_use_fpga) {
    if (g_use_double) {
        batch = javaData.getBatchDouble();
        shacc_pairhmm::calculate_double()
    } else {
        batch = javaData.getBatch();
        shacc_pairhmm::calculate()
    }
}
```

With this, if the GKL is called with the `use_double` and `use_fpga` option set to true it would call the new stub or if linked with a library that calls a FPGA implementation use the FPGA implementation.

Edit : Lines 74-76 in IntelPairHmm.java should also be changed.
```
if (args.useDoublePrecision && useFpga) {
    logger.warn("FPGA PairHMM does not support double precision floating-point. Using AVX PairHMM");
}
```

**Comment by gspowley** [comment]
@mepowers, can you please respond to this request?

**Comment by mepowers** [comment]
@rick-heig - I missed this notification - my apologies.

Our team specifically doesn't have plans to take on new FPGA development work, but I know our FPGA product group is still working in genomics, and we have active external collaborations in this space.  @aprabhak2 - please feel free to chime in if you have input here.

It looks like HaplotypeCaller can be run with a doubleprecision flag for pairHMM:  https://software.broadinstitute.org/gatk/documentation/tooldocs/current/org_broadinstitute_hellbender_tools_walkers_haplotypecaller_HaplotypeCaller.php

... and doing so "is slower but matches the java implementation better."

For the FPGA implementation of pairHMM, I would expect similar results, ie slower but better matching the java implementation.  I'll let @aprabhak2 correct if that's wrong.
