### ISSUE TITLE
GKL hangs on kernel update

### ISSUE THREAD

**Issue by jonn-smith** [Intel-HLS/GKL#98]
It looks like a GATK user is experiencing a GKL hang since they updated their kernel (4.4 -> 4.12, SUSE Linux, SLES15, CPUs: Xeon E5-2697 v4 and Xeon Gold 6148 CPUs).  They detailed their findings in a forum post:

https://gatkforums.broadinstitute.org/gatk/discussion/23342/inteldeflater-problem-on-kernel-update/p1  

@gspowley - Can you take a look and see if you can make more sense of it?

**Comment by gspowley** [comment]
@mepowers, can you please take a look at this issue?

**Comment by mepowers** [comment]
@jonn-smith I replied on the thread, asking berutti to provide any updates here.  Apologies for the lag time on this.

**Comment by mepowers** [comment]
Haven't heard back from the user.  On GATK 3.X as well.  Sync'd with Broad; closing this.
